import { fireEvent, render, screen } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import { SearchableOptionPickerPopoverContent } from '../../modules/tickets/components/SearchableOptionPickerPopoverContent';
import { TicketAssignmentSubMenu } from '../../modules/tickets/components/TicketAssignmentSubMenu';
import type { Ticket } from '../../context/TicketContextContext';
const options = (count: number) => Array.from({ length: count }, (_, id) => ({ id: `${id}`, label: `Option ${id}` }));
it.each([1000, 5000])('bounds and searches %i options with keyboard pagination', count => {
  const onToggle = vi.fn();
  const start = performance.now();
  const { container } = render(<SearchableOptionPickerPopoverContent title="Labels" searchPlaceholder="Search" options={options(count)} selectedIds={new Set(['50'])} onToggle={onToggle} />);
  expect(screen.getAllByRole('checkbox')).toHaveLength(50);
  expect(container.querySelectorAll('*').length).toBeLessThan(300);
  const initialMs = performance.now() - start;
  const last = screen.getAllByRole('checkbox')[49];
  last.focus();
  fireEvent.keyDown(last, { key: 'ArrowDown' });
  expect(screen.getByRole('checkbox', { name: 'Option 50' })).toHaveFocus();
  expect(screen.getByRole('checkbox', { name: 'Option 50' })).toBeChecked();
  fireEvent.click(document.activeElement!);
  expect(onToggle).toHaveBeenCalledWith('50', true);
  fireEvent.keyDown(document.activeElement!, { key: 'ArrowUp' });
  expect(screen.getByRole('checkbox', { name: 'Option 49' })).toHaveFocus();
  fireEvent.keyDown(document.activeElement!, { key: 'End' });
  expect(screen.getByRole('checkbox', { name: `Option ${count - 1}` })).toHaveFocus();
  fireEvent.keyDown(document.activeElement!, { key: 'Home' });
  expect(screen.getByRole('checkbox', { name: 'Option 0' })).toHaveFocus();
  fireEvent.click(screen.getByRole('button', { name: 'Next page' }));
  expect(screen.getByRole('checkbox', { name: 'Option 50' })).toHaveFocus();
  const searchStart = performance.now();
  fireEvent.change(screen.getByRole('textbox'), { target: { value: `Option ${count - 1}` } });
  expect(screen.getAllByRole('checkbox')).toHaveLength(1);
  expect(screen.getByRole('checkbox', { name: `Option ${count - 1}` })).toBeInTheDocument();
  expect(screen.getByRole('status')).toHaveTextContent('Showing 1–1 of 1');
  console.info({ picker: 'options', count, initialMs, searchMs: performance.now() - searchStart });
});
it.each([1000, 5000])('bounds and searches %i assignment results', count => {
  const tickets = options(count).map(o => ({ id: o.id, key: `GRA-${o.id}`, title: o.label })) as Ticket[];
  const onSelectTicket = vi.fn();
  const start = performance.now();
  const { container } = render(<TicketAssignmentSubMenu title="Assign" description="Choose ticket" searchPlaceholder="Search" tickets={tickets} emptyStateLabel="No tickets" onSelectTicket={onSelectTicket} />);
  expect(screen.getAllByRole('menuitem')).toHaveLength(52);
  expect(container.querySelectorAll('*').length).toBeLessThan(400);
  const initialMs = performance.now() - start;
  fireEvent.keyDown(screen.getByRole('textbox'), { key: 'ArrowDown' });
  expect(screen.getByRole('menuitem', { name: 'GRA-0 Option 0' })).toHaveFocus();
  fireEvent.keyDown(document.activeElement!, { key: 'PageDown' });
  expect(screen.getByRole('menuitem', { name: 'GRA-50 Option 50' })).toHaveFocus();
  fireEvent.keyDown(document.activeElement!, { key: 'Enter' });
  expect(onSelectTicket).toHaveBeenCalledWith(tickets[50]);
  const searchStart = performance.now();
  fireEvent.change(screen.getByRole('textbox'), { target: { value: `GRA-${count - 1}` } });
  expect(screen.getAllByRole('menuitem')).toHaveLength(1);
  console.info({ picker: 'assignment', count, initialMs, searchMs: performance.now() - searchStart });
});
it('preserves button selection and resets pages when authorized options change', () => {
  const props = { title: 'Projects', searchPlaceholder: 'Search', selectedIds: new Set(['50']), onToggle: vi.fn(), showCheckbox: false };
  const { rerender } = render(<SearchableOptionPickerPopoverContent {...props} options={options(100)} />);
  fireEvent.click(screen.getByRole('button', { name: 'Next page' }));
  expect(screen.getByRole('button', { name: 'Option 50' })).toHaveFocus();
  expect(screen.getByRole('button', { name: 'Option 50' })).toHaveAttribute('aria-pressed', 'true');
  rerender(<SearchableOptionPickerPopoverContent {...props} options={options(2)} />);
  expect(screen.getByRole('button', { name: 'Option 0' })).toHaveFocus();
  expect(screen.queryByText('Next page')).not.toBeInTheDocument();
});

it('returns focus to search when the focused result is removed', () => {
  const props = { title: 'Projects', searchPlaceholder: 'Search', selectedIds: new Set<string>(), onToggle: vi.fn() };
  const { rerender } = render(<SearchableOptionPickerPopoverContent {...props} options={options(100)} />);
  screen.getAllByRole('checkbox')[0].focus();
  rerender(<SearchableOptionPickerPopoverContent {...props} options={[]} />);
  expect(screen.getByRole('textbox')).toHaveFocus();
  expect(screen.getByRole('status')).toHaveTextContent('No results');
});
