services:
  backend:
    develop:
      watch:
        - action: sync
          path: ../server/src
          target: /app/server/src
          ignore:
            - node_modules/
            - dist/
            - coverage/
            - tests/
        - action: rebuild
          path: ../server/package.json
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ../server/tsconfig.json
        - action: sync
          path: ../library
          target: /app/library
          ignore:
            - node_modules/
            - dist/

  frontend:
    develop:
      watch:
        - action: sync
          path: ../client/src
          target: /app/client/src
          ignore:
            - node_modules/
            - dist/
            - coverage/
            - src/test/
            - tests/
        - action: rebuild
          path: ../client/package.json
        - action: rebuild
          path: ../client/tsconfig.json
        - action: sync
          path: ../library
          target: /app/library
          ignore:
            - node_modules/
            - dist/